const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const intakeQuestions = [
 {id:'issues',title:'Current issues',prompt:'In a few sentences please describe the issues you have been experiencing',type:'text'},
 {id:'hospitalized',title:'Treatment history',prompt:'Have you ever been hospitalized for a reason related to your mental health?',type:'choice',options:['Yes','No']},
 {id:'benzo',title:'Benzodiazepine medications',prompt:'Are you currently taking benzodiazepine medication?',help:'Examples: Clonazepam, Klonopin, Diazepam, Valium, Alprazolam, Xanax, Lorazepam, Ativan, Chlordiazepoxide, Librium, Temazepam, Restoril.',type:'choice',options:['Yes','No']},
 {id:'medications',title:'Previous medications',prompt:'Please list any other psychiatric medications you have previously used and describe your experiences with them.',type:'text'},
 {id:'pcp',title:'Primary care provider',prompt:'Who is your primary care provider? You can also answer “I don’t have one” or “I’m not sure.”',type:'text'},
 {id:'conditions',title:'Medical conditions',prompt:'List your current medical conditions and any relevant past illnesses or surgeries. If none, enter “None.”',type:'text'},
 {id:'allergies',title:'Allergies',prompt:'List any medication or other allergies and your reactions. If none, enter “None known.”',type:'text'},
 {id:'currentMeds',title:'Current medications',prompt:'List medications and supplements you currently take, including dose and frequency when known.',type:'text'},
 {id:'therapy',title:'Previous care',prompt:'Tell us about previous diagnoses, therapy, or other mental health treatment. It is okay if you do not have documents.',type:'text'},
 {id:'family',title:'Family history',prompt:'Share any relevant family medical or mental health history, or enter “Unknown.”',type:'text'},
 {id:'dailyLife',title:'Daily life and support',prompt:'Tell us about sleep, work, relationships, and the people who support you.',type:'text'},
 {id:'substances',title:'Alcohol, tobacco and other substances',prompt:'Tell us what you use and how often, or enter “None.”',type:'text'},
 {id:'emergencyName',title:'Emergency contact',prompt:'Full name and relationship',type:'text',group:'contact'},
 {id:'emergencyPhone',title:'Emergency contact phone',prompt:'Include the area code.',type:'text',group:'contact'},
 {id:'vitals',title:'Most recent vital signs',prompt:'If available, share blood pressure, heart rate, and the date measured. Otherwise, enter “Not available.”',type:'text',group:'vitals'},
 ...['Feeling nervous, anxious or on edge','Not being able to stop or control worrying','Worrying too much about different things','Trouble relaxing','Being so restless that it is hard to sit still','Becoming easily annoyed or irritable','Feeling afraid as if something awful might happen'].map((prompt,i)=>({id:`gad${i+1}`,title:`${i+1}. ${prompt}`,prompt:'',type:'choice',options:['Not at all','Several days','More than half the days','Nearly every day'],group:'gad'}))
];
export function createIntakeState(){return {tab:'web',previewOnly:false,demoIndex:0,recordStatus:'',prefilled:{},editing:{},edited:{},drafts:{},signature:null,uploads:{},release:false,recordsForm:{gender:'',address:'',city:'',state:'',zip:''},answers:{},smsConsent:false,stopped:false,unread:1,records:'idle',imported:{},call:'idle',error:'',safety:false,reviewed:false};}
export function applyIntakeScenario(intake,status){
 if(intake.appliedScenario===status)return;
 intake.appliedScenario=status;
 if(!['found','ready'].includes(status))return;
 const records={hospitalized:'No',benzo:'No',medications:'Sertraline documented in the most recent medication list. Please confirm current dose and any previous medications.',pcp:'Dr. Maya Patel · Oakwood Family Care',conditions:'No other medical conditions documented in the available records.',allergies:'No known medication allergies documented.',currentMeds:'Sertraline 50 mg once daily — confirm this is still current.',therapy:'Anxiety diagnosis documented; previous outpatient therapy.',family:'Family history not documented in available records.'};
 Object.entries(records).forEach(([key,value])=>{if(!intake.answers[key]){intake.answers[key]=value;intake.prefilled[key]='records';}});
 if(status==='ready'){
 const text={issues:'I’ve been feeling anxious most days, especially at work. It’s getting harder to focus and sleep.',gad1:'Nearly every day',gad2:'More than half the days',gad3:'Several days',dailyLife:'Anxiety at work is affecting my focus and sleep. I have support from my partner.',substances:'An occasional glass of wine. No tobacco or other substances.'};
 Object.entries(text).forEach(([key,value])=>{if(!intake.answers[key]){intake.answers[key]=value;intake.prefilled[key]='text';}});
 }
}
export function saveIntakeEdit(intake,key){intake.answers[key]=(intake.drafts[key]??intake.answers[key]??'').trim();delete intake.drafts[key];intake.editing[key]=false;intake.edited[key]=true;intake.signature=null;intake.reviewed=false;}
export function canFinalizeIntake(intake){return intakeQuestions.every(q=>Boolean(intake.answers[q.id]?.trim()))&&!Object.values(intake.editing).some(Boolean)&&Boolean(intake.uploads.id);}
export function isIntakeComplete(intake){return canFinalizeIntake(intake)&&Boolean(intake.signature);}
export function nextQuestion(intake){return intakeQuestions.find(q=>!intake.answers[q.id]?.trim());}
export function normalizeReply(question,reply){const text=reply.trim();if(!text)return null;if(question.type!=='choice')return text;return question.options.find(o=>o.toLowerCase()===text.toLowerCase())||null;}
const privacy='Text messages are not end-to-end encrypted. Someone with access to your phone or messages may be able to read your health information.';
export function mountIntake(root,intake,{name,patient={},appointment,insurance,insuranceComplete=false,reviewInsurance}){
 root.cleanupIntake?.();root.cleanupIntake=()=>stopDemo();
 const action=(id,label,cls='secondary')=>`<button type="button" class="${cls}" data-intake="${id}">${label}</button>`;
 const bubble=(text,who='legion')=>`<div class="message ${who}"><small>${who==='legion'?'Legion Health':'You'}</small><p>${esc(text)}</p></div>`;
 let demoTimer=null;
 const textDemo=[['legion','Before your visit, what has been feeling hardest lately?'],['you','I’ve been feeling anxious most days, especially at work. It’s getting harder to focus and sleep.'],['legion','Thank you for sharing that. When did you first notice the anxiety starting to affect your sleep?'],['you','A few months ago. I usually lie awake for an hour or two thinking about everything I need to do.'],['legion','That sounds exhausting. We’ll make sure your provider has this context before your appointment.'],['legion','GAD-7 check-in: over the last 2 weeks, how often have you felt nervous, anxious, or on edge?'],['you','Nearly every day.'],['legion','Over the last 2 weeks, how often have you been bothered by not being able to stop or control worrying?'],['you','More than half the days.'],['legion','And worrying too much about different things, over the last 2 weeks?'],['you','Several days.'],['legion','Thanks. Are you currently taking any medication for anxiety or another mental health concern?'],['you','I take sertraline every morning, and I’m not taking anything else right now.'],['legion','Got it. We’ll confirm your medication and dosage with you before your visit.']];
 const phoneDemo=[['legion',`Hi ${name}, this is Legion’s automated AI intake assistant. Is now a private and convenient time? This call is not an emergency service. It’ll just take five minutes to collect information about how you’re doing in advance of your appointment.`],['you','Yes, that’s okay.'],['legion','Thanks. To start, what has been feeling hardest lately?'],['you','I’ve been feeling anxious most days, especially at work. It’s getting harder to focus and sleep.'],['legion','Thank you for sharing that. I’ll save this for your care team and ask a few more questions.']];
 const demoBubble=(text,who)=>`<div class="message ${who}"><small>${who==='legion'?'Legion Health':'You'}</small><p>${esc(text)}</p></div>`;
 function demoTyping(){return '<div class="typing-indicator" aria-label="Legion Health is typing"><i></i><i></i><i></i></div>';}
 function startDemo(){if(demoTimer||!intake.previewOnly)return;demoTimer=setInterval(()=>{const total=intake.tab==='text'?textDemo.length:phoneDemo.length;if(intake.demoIndex<total){intake.demoIndex+=1;draw();}else{clearInterval(demoTimer);demoTimer=null;}},2600);}
 function stopDemo(){if(demoTimer){clearInterval(demoTimer);demoTimer=null;}}
 function records(){
  const status=intake.recordStatus;
  const titles={'':'Connect your medical records',checking:'We’re checking for available records',still:'We’re still checking for available records',found:'Some records are available',ready:'Records and text answers are ready to review'};
  const pending=['checking','still'].includes(status);
  const details=pending?'This may take a little while. We’ll text you when it’s complete. You can continue your intake in the meantime.':status?'Review the suggested answers below and edit anything that needs correcting.':'Reduce how much you need to fill in. Connect available records to help prepare for your care.';
  const form={...patient,...intake.recordsForm};
  const field=(key,label,type='text',extra='')=>`<label class="field">${label}<input name="${key}" type="${type}" value="${esc(form[key]||'')}" ${extra}></label>`;
  return `<section class="records-hero"><div><div class="eyebrow">Less paperwork, more time for you</div><h2>${titles[status]||titles['']}</h2><p>${details}</p><small>${status?'You can edit your answers at any time.':'Optional · Continue without connecting if you prefer.'}</small></div>${!status?action('records','Connect records','primary'):''}</section>
  ${intake.records==='review'?`<dialog class="records-modal" aria-labelledby="records-modal-title"><button class="dialog-close" type="button" data-intake="skip-records" aria-label="Close">×</button><h2 id="records-modal-title">Help us find your records</h2><p>Check your details and add the missing information so we can look for your available medical records.</p><form id="records-form"><div class="field-grid">${field('first','First name','text','required')}${field('last','Last name','text','required')}${field('dob','Date of birth','date','required')}${field('email','Email','email')}${field('phone','Phone number','tel')}<label class="field">Sex assigned at birth<select name="gender" required><option value="">Select</option>${[['F','Female'],['M','Male'],['O','Other'],['U','Unknown']].map(([value,label])=>`<option value="${value}" ${form.gender===value?'selected':''}>${label}</option>`).join('')}</select></label>${field('address','Street address','text','required')}${field('city','City','text','required')}${field('state','State','text','required maxlength="2" placeholder="TX"')}${field('zip','ZIP code','text','required pattern="[0-9]{5}" inputmode="numeric"')}</div><label class="check-label"><input name="permission" type="checkbox" required><span>I allow Legion Health to retrieve available medical records for my care.</span></label><div class="inline-actions"><button type="submit" class="primary">Connect records</button>${action('skip-records','Continue without connecting')}</div></form></dialog>`:''}`;
 }
 function documents(){return `<section class="intake-section"><h2>Documents &amp; permissions</h2><p>Add your photo ID. Supporting diagnosis and treatment documents are optional if you have them available.</p>${[['id','Photo ID','Required'],['diagnosis','Diagnosis documents','Optional'],['treatment','Treatment history documents','Optional']].map(([key,title,hint])=>`<div class="upload-field"><label class="field">${title} <small>${hint}</small><input type="file" data-upload="${key}" accept="image/jpeg,image/png,application/pdf"></label>${intake.uploads[key]?`<p class="upload-status">✓ ${esc(intake.uploads[key].name)} ${action('remove-upload-'+key,'Remove','text-button')}</p>`:''}</div>`).join('')}<details class="release-details"><summary>Release of information (optional)</summary><p>If you would like Legion to coordinate with another provider, add their details and choose what may be shared.</p><label class="field">Provider or practice<input data-release="provider" value="${esc(intake.releaseProvider||'')}"></label><label class="field">Information to share<input data-release="scope" value="${esc(intake.releaseScope||'')}" placeholder="For example, medication list and treatment history"></label><label class="check-label"><input type="checkbox" data-release="permission" ${intake.release?'checked':''}><span>I authorize Legion Health to coordinate my care with the provider named above using the information I have specified.</span></label></details></section>`;}
 function web(){
 const field=q=>{
 const editing=!!intake.editing[q.id],value=editing?(intake.drafts[q.id]??intake.answers[q.id]??''):(intake.answers[q.id]||'');
 const source=intake.prefilled[q.id],display=!!value&&!editing;
 const control=q.type==='choice'?`<select id="intake-${q.id}" data-answer="${q.id}"><option value="">Choose an answer</option>${q.options.map(o=>`<option ${value===o?'selected':''}>${o}</option>`).join('')}</select>`:`<textarea id="intake-${q.id}" data-answer="${q.id}" rows="3">${esc(value)}</textarea>`;
 return `<div class="intake-field ${display?'autofilled':''}"><label for="intake-${q.id}"><strong>${q.title}</strong><span>${q.prompt}</span></label>${q.help?`<p class="fine-print">${q.help}</p>`:''}${display?`<div class="autofill-value"><span>${esc(value)}</span>${source?`<span class="autofill-source">${source==='records'?'From connected records':'From text intake'}${intake.edited[q.id]?' · Edited by you':''}</span>`:''}${action('edit-'+q.id,'✎ Edit','text-button')}</div>`:`${control}<div class="inline-actions">${action('save-'+q.id,'Save answer','secondary')}${editing?action('cancel-'+q.id,'Cancel','text-button'):''}</div>`}</div>`;
 };
 const gad=intakeQuestions.filter(q=>q.group==='gad'),answered=gad.filter(q=>intake.answers[q.id]).length;
 return `<div id="intake-web" class="intake-card"><div class="eyebrow">Your health history</div><h2>Tell your story once</h2><p>Anything you share by text or phone appears here too. You can change your answers at any time.</p><div class="alternate-intake"><strong>Prefer a different way to answer?</strong><span>We can also collect your answers by text or walk you through the questions by phone.</span><div class="inline-actions">${action('text-me','Text me instead')}${action('call-me','Call me instead')}</div></div>${intakeQuestions.filter(q=>!q.group).map(field).join('')}<section class="intake-section"><h2>Emergency contact</h2>${intakeQuestions.filter(q=>q.group==='contact').map(field).join('')}</section><section class="intake-section"><h2>Recent vital signs</h2>${intakeQuestions.filter(q=>q.group==='vitals').map(field).join('')}</section>${documents()}<section class="gad-section"><h2>GAD-7 Anxiety Assessment</h2><p>Over the last 2 weeks, how often have you been bothered by the following problems?</p><p class="fine-print">${answered} of 7 answered · Text answers are labeled below.</p>${gad.map(field).join('')}<a class="fine-print" href="https://www.hiv.uw.edu/page/mental-health-screening/gad-7" target="_blank" rel="noopener">About the GAD-7 questionnaire</a></section><section class="signature-section"><h2>Sign to finalize your answers</h2>${intake.signature?`<div class="banner" role="status">Signed by ${esc(intake.signature.name)} · ${esc(intake.signature.date)}<br>Your answers are finalized. Editing an answer will require a new signature.</div>`:`<p>Save and review the answers above, then add your digital signature.</p><form id="intake-signature"><label class="field">Full name<input name="signature" required autocomplete="name" placeholder="Type your full name"></label><label class="check-label"><input type="checkbox" name="confirm" required><span>I confirm these answers are accurate to the best of my knowledge and agree to sign electronically.</span></label><button type="submit" class="primary">Sign &amp; finalize</button></form>`}<p class="fine-print">Your signature finalizes your medical history and pre-appointment check-in. You can return to edit your information at any time.</p></section></div>`;
 }

 function sms(){const visible=textDemo.slice(0,intake.demoIndex);return `<section class="phone-frame"><div class="phone-header"><span class="feedback-avatar">♡</span><div><strong>Legion Health</strong><small>Messages</small></div></div><div class="message-log">${visible.map(([who,text])=>demoBubble(text,who==='you'?'you':'legion')).join('')}${intake.demoIndex<textDemo.length?demoTyping():''}</div></section>`;}
 function phone(){const visible=phoneDemo.slice(0,intake.demoIndex);return `<section class="phone-frame"><div class="phone-header"><span class="feedback-avatar">☎</span><div><strong>Legion Health</strong><small>Intake call</small></div></div><div class="message-log">${visible.map(([who,text])=>demoBubble(text,who==='you'?'you':'legion')).join('')}${intake.demoIndex<phoneDemo.length?demoTyping():''}</div></section>`;}
 function draw(){const complete=isIntakeComplete(intake);const count=intakeQuestions.filter(q=>intake.answers[q.id]?.trim()).length;const channel=intake.tab==='text'?sms():phone();if(intake.previewOnly&&intake.tab!=='web'){stopDemo();startDemo();root.innerHTML=`<div class="channel-preview"><div class="channel-preview-top"><h1>${intake.tab==='text'?'Text intake':'Phone intake'}</h1></div>${channel}</div>`;const log=root.querySelector('.message-log');if(log)log.scrollTop=log.scrollHeight;return;}stopDemo();root.innerHTML=`<div class="post-intake"><div class="intake-title"><div><div class="eyebrow">Appointment booked</div><h1>Get ready for your visit, ${esc(name)}</h1><p>Prepare at your own pace. The web form is always available; the Text and Phone options are available when Legion reaches out.</p></div></div>${records()}<div class="intake-layout"><div>${intake.error?`<div class="notice" role="alert">${esc(intake.error)}</div>`:''}${intake.reviewed?`<div class="banner" role="status">Your medical history and check-in are complete. Your answers are ready for your care team.</div>`:''}${intake.tab==='web'?web():intake.tab==='text'?sms():phone()}</div><aside class="intake-summary"><section class="intake-card"><h3>Your appointment</h3>${appointment}</section><section class="intake-card"><h3>Before your visit</h3><div class="readiness"><strong>Insurance <span class="status-tag ${insuranceComplete?'complete':'incomplete'}">${insuranceComplete?'✓ Complete':'Incomplete'}</span></strong><p>${esc(insurance)}</p>${action('insurance','Review insurance')}</div><div class="readiness"><strong>Medical history &amp; check-in <span class="status-tag ${complete?'complete':'incomplete'}">${complete?'✓ Complete':'Incomplete'}</span></strong><p id="intake-count">${count} of ${intakeQuestions.length} questions saved</p><progress max="${intakeQuestions.length}" value="${count}"></progress></div><ul class="intake-checklist"><li>${count===intakeQuestions.length?'✓':'○'} Medical history and GAD-7 answers</li><li>${intake.uploads.id?'✓':'○'} Photo ID</li><li>${complete?'✓':'○'} Review and digital signature</li></ul><p class="fine-print">${complete?'You’re ready for your appointment.':'Save your answers, add your ID, and sign to complete your intake. Supporting records are optional.'}</p></section></aside></div></div>`;const modal=root.querySelector('.records-modal');if(modal){modal.showModal();modal.oncancel=e=>{e.preventDefault();intake.records='idle';draw();};}}
 function answer(raw){const q=nextQuestion(intake);if(!q)return;const value=normalizeReply(q,raw);if(!value){intake.error='Please choose one of the listed responses, or use the web form to review your answer.';return;}intake.answers[q.id]=value;intake.reviewed=false;}
 root.onclick=e=>{const button=e.target.closest('[data-intake]');if(!button)return;e.preventDefault();const id=button.dataset.intake;intake.error='';if(['web','text','phone'].includes(id)){intake.tab=id;intake.previewOnly=id!=='web';intake.demoIndex=0;if(id==='text')intake.unread=0;}
 else if(id==='records')intake.records=intake.records==='connected'?'connected':'review';
 else if(id==='skip-records'||id==='disconnect'){intake.records='idle';intake.imported={};}
 else if(id==='no-records'){intake.records='empty';intake.imported={};}
 else if(id.startsWith('import-')){const key=id.slice(7);intake.answers[key]=intake.imported[key];delete intake.imported[key];intake.reviewed=false;}
 else if(id.startsWith('remove-upload-')){delete intake.uploads[id.slice(14)];intake.signature=null;intake.reviewed=false;}
 else if(id.startsWith('edit-')){const key=id.slice(5);intake.signature=null;intake.reviewed=false;intake.editing[key]=true;intake.drafts[key]=intake.answers[key]||'';}
 else if(id.startsWith('save-')){saveIntakeEdit(intake,id.slice(5));}
 else if(id.startsWith('cancel-')){const key=id.slice(7);delete intake.drafts[key];intake.editing[key]=false;}
 else if(id==='review')intake.reviewed=true;
 else if(id==='call'){intake.tab='phone';intake.call='active';intake.callConsent=false;}
 else if(id==='text-me'){intake.tab='text';intake.previewOnly=true;intake.demoIndex=0;intake.unread=0;}
 else if(id==='call-me'){intake.tab='phone';intake.previewOnly=true;intake.demoIndex=0;intake.call='active';intake.callConsent=false;}
 else if(id==='call-consent')intake.callConsent=true;
 else if(id==='end-call')intake.call='ended';
 else if(id==='insurance'){reviewInsurance();return;}
 draw();};
 root.onchange=e=>{const key=e.target.dataset.upload;if(key){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','application/pdf'].includes(file.type)||file.size>20*1024*1024){intake.error='Please choose a JPG, PNG, or PDF under 20 MB.';}else{intake.uploads[key]={name:file.name,size:file.size};intake.signature=null;intake.reviewed=false;intake.error='';}draw();return;}if(e.target.dataset.release==='permission'){intake.release=e.target.checked;intake.signature=null;intake.reviewed=false;}};
 root.oninput=e=>{if(e.target.dataset.release){intake.signature=null;intake.reviewed=false;const key=e.target.dataset.release;if(key==='provider')intake.releaseProvider=e.target.value;if(key==='scope')intake.releaseScope=e.target.value;return;}const key=e.target.dataset.answer;if(!key)return;intake.drafts[key]=e.target.value;intake.editing[key]=true;};
 root.onsubmit=e=>{if(e.target.id==='intake-signature'){e.preventDefault();if(intake.release&&(!intake.releaseProvider?.trim()||!intake.releaseScope?.trim())){intake.error='Add the provider and information to share for your optional release, or uncheck the permission.';draw();root.querySelector('[role=alert]')?.scrollIntoView({block:'center'});return;}if(!canFinalizeIntake(intake)){intake.error='Please save every answer, add your photo ID, and save any edits before signing.';draw();root.querySelector('[role=alert]')?.scrollIntoView({block:'center',behavior:'smooth'});return;}const fd=new FormData(e.target);const signedName=String(fd.get('signature')||'').trim();if(!signedName)return;intake.signature={name:signedName,date:new Date().toLocaleDateString()};intake.reviewed=true;draw();root.querySelector('.signature-section')?.scrollIntoView({block:'center',behavior:'smooth'});return;}if(e.target.id==='records-form'){e.preventDefault();intake.recordsForm=Object.fromEntries(new FormData(e.target));intake.records='pending';intake.recordStatus='checking';document.getElementById('scenario-records').value='checking';draw();return;}if(!['sms-reply','phone-reply'].includes(e.target.id))return;e.preventDefault();const raw=new FormData(e.target).get('reply').trim(),cmd=raw.toUpperCase();intake.error='';if(e.target.id==='sms-reply'){
 if(['STOP','UNSUBSCRIBE','CANCEL','END','QUIT'].includes(cmd)){intake.stopped=true;intake.smsConsent=false;}
 else if(cmd==='START'){intake.stopped=false;intake.smsConsent=false;}
 else if(cmd==='HELP'){intake.error='You can switch to the web form at any time. Contact your care team for help. For immediate danger, call 911; for crisis support, call or text 988.';}
 else if(intake.stopped)intake.error='Texts are stopped. Reply START to choose texting again, or use the web form.';
 else if(!intake.smsConsent){intake.smsConsent=true;answer(raw);}
 else if(/suicid|kill myself|hurt myself|harm myself|hurt someone/i.test(raw)){intake.safety=true;intake.error='Please use the crisis guidance below. This inbox is not continuously monitored.';}
 else answer(raw);
 }else answer(raw);draw();};
 draw();
}
