const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const intakeQuestions = [
 {id:'issues',title:'Current issues',prompt:'In a few sentences please describe the issues you have been experiencing',type:'text'},
 {id:'hospitalized',title:'Treatment history',prompt:'Have you ever been hospitalized for a reason related to your mental health?',type:'choice',options:['Yes','No']},
 {id:'benzo',title:'Benzodiazepine medications',prompt:'Are you currently taking benzodiazepine medication?',help:'Examples: Clonazepam, Klonopin, Diazepam, Valium, Alprazolam, Xanax, Lorazepam, Ativan, Chlordiazepoxide, Librium, Temazepam, Restoril.',type:'choice',options:['Yes','No']},
 {id:'medications',title:'Previous medications',prompt:'Please list any other psychiatric medications you have previously used and describe your experiences with them.',type:'text'},
 {id:'pcp',title:'Primary care provider',prompt:'Who is your primary care provider? You can also answer “I don’t have one” or “I’m not sure.”',type:'text'},
 {id:'anxiety',title:'Anxiety check-in',prompt:'Over the last 2 weeks, how often have you been bothered by feeling nervous, anxious, or on edge?',type:'choice',options:['Not at all','Several days','Over half the days','Nearly every day']}
];
export function createIntakeState(){return {tab:'web',previewOnly:false,demoIndex:0,answers:{},smsConsent:false,stopped:false,unread:1,records:'idle',imported:{},call:'idle',error:'',safety:false,reviewed:false};}
export function nextQuestion(intake){return intakeQuestions.find(q=>!intake.answers[q.id]?.trim());}
export function normalizeReply(question,reply){const text=reply.trim();if(!text)return null;if(question.type!=='choice')return text;return question.options.find(o=>o.toLowerCase()===text.toLowerCase())||null;}
const privacy='Text messages are not end-to-end encrypted. Someone with access to your phone or messages may be able to read your health information.';
export function mountIntake(root,intake,{name,appointment,insurance,reviewInsurance}){
 const action=(id,label,cls='secondary')=>`<button type="button" class="${cls}" data-intake="${id}">${label}</button>`;
 const bubble=(text,who='legion')=>`<div class="message ${who}"><small>${who==='legion'?'Legion Health':'You'}</small><p>${esc(text)}</p></div>`;
 let demoTimer=null;
 const textDemo=[['legion','Before your visit, what has been feeling hardest lately?'],['you','I’ve been feeling anxious most days, especially at work. It’s getting harder to focus and sleep.'],['legion','Thank you for sharing that. When did you first notice the anxiety starting to affect your sleep?'],['you','A few months ago. I usually lie awake for an hour or two thinking about everything I need to do.'],['legion','That sounds exhausting. We’ll make sure your provider has this context before your appointment.']];
 const phoneDemo=[['legion',`Hi ${name}, this is Legion’s automated AI intake assistant. Is now a private and convenient time? This call is not an emergency service. It’ll just take five minutes to collect information about how you’re doing in advance of your appointment.`],['you','Yes, that’s okay.'],['legion','Thanks. To start, what has been feeling hardest lately?'],['you','I’ve been feeling anxious most days, especially at work. It’s getting harder to focus and sleep.'],['legion','Thank you for sharing that. I’ll save this for your care team and ask a few more questions.']];
 const demoBubble=(text,who)=>`<div class="message ${who}"><small>${who==='legion'?'Legion Health':'You'}</small><p>${esc(text)}</p></div>`;
 function demoTyping(){return '<div class="typing-indicator" aria-label="Legion Health is typing"><i></i><i></i><i></i></div>';}
 function startDemo(){if(demoTimer||!intake.previewOnly)return;demoTimer=setInterval(()=>{const total=intake.tab==='text'?textDemo.length:phoneDemo.length;if(intake.demoIndex<total){intake.demoIndex+=1;draw();}else{clearInterval(demoTimer);demoTimer=null;}},2600);}
 function stopDemo(){if(demoTimer){clearInterval(demoTimer);demoTimer=null;}}
 function records(){return `<section class="records-hero"><div><div class="eyebrow">Less paperwork, more time for you</div><h2>Connect your medical records</h2><p>Reduce how much you need to fill in. Review available history with your care team and add anything missing.</p><small>Optional · You can keep answering while we look for records.</small></div>${action('records',intake.records==='connected'?'Review connected records':'Connect records','primary')}</section>${intake.records==='review'?`<section class="intake-card"><h3>Find your available records</h3><p>With your permission, Legion can use Metriport to look for records from your previous care. We may find medications, diagnoses, visits, and provider details. Not every record may be available.</p><label class="check-label"><input id="record-permission" type="checkbox">I allow Legion Health to retrieve available medical records for my care.</label><div class="inline-actions">${action('connect','Connect my records','primary')}${action('skip-records','Continue without connecting')}</div></section>`:''}${intake.records==='connected'?`<section class="intake-card"><span class="context-chip ok">Records available to review</span><h3>Confirm what’s still accurate</h3><p>Records can be incomplete or out of date. These suggestions won’t fill your answers until you confirm them.</p>${Object.entries(intake.imported).map(([id,value])=>`<div class="record-row"><div><strong>${intakeQuestions.find(q=>q.id===id).title}</strong><p>${esc(value)}</p><small>Source: prior care summary · Needs your confirmation</small></div>${action('import-'+id,'Use this information')}</div>`).join('')}<p class="fine-print">A medication in a past record does not mean you are taking it today. Please add your experience with prior medications.</p>${action('no-records','Show no records found')}${action('disconnect','Disconnect')}</section>`:''}${intake.records==='empty'?'<div class="notice">No records were found. You can still complete your history here, by text, or by phone. You can add documents later.</div>':''}`;}
 function web(){return `<div id="intake-web" class="intake-card"><div class="eyebrow">Your health history</div><h2>Tell your story once</h2><p>Anything you share by text or phone appears here too. You can change your answers at any time.</p><div class="alternate-intake"><strong>Prefer a different way to answer?</strong><span>We can also collect your answers by text or walk you through the questions by phone.</span><div class="inline-actions">${action('text-me','Text me instead')}${action('call-me','Call me instead')}</div></div>${intakeQuestions.map(q=>`<div class="intake-field"><label for="intake-${q.id}"><strong>${q.title}</strong><span>${q.prompt}</span></label>${q.help?`<p class="fine-print">${q.help}</p>`:''}${q.type==='choice'?`<select id="intake-${q.id}" data-answer="${q.id}"><option value="">Choose an answer</option>${q.options.map(o=>`<option ${intake.answers[q.id]===o?'selected':''}>${o}</option>`).join('')}</select>`:`<textarea id="intake-${q.id}" data-answer="${q.id}" rows="3">${esc(intake.answers[q.id])}</textarea>`}<small>${intake.answers[q.id]?'Saved':'Not answered yet'}</small></div>`).join('')}${action('review','Review my answers','primary')}<p class="fine-print">This covers the questions shown here. Additional health-history sections and assessment questions still need to be completed before your visit.</p></div>`;}
 function sms(){const visible=textDemo.slice(0,intake.demoIndex);return `<section class="phone-frame"><div class="phone-header"><span class="feedback-avatar">♡</span><div><strong>Legion Health</strong><small>Messages</small></div></div><div class="message-log">${visible.map(([who,text])=>demoBubble(text,who==='you'?'you':'legion')).join('')}${intake.demoIndex<textDemo.length?demoTyping():''}</div></section>`;}
 function phone(){const visible=phoneDemo.slice(0,intake.demoIndex);return `<section class="phone-frame"><div class="phone-header"><span class="feedback-avatar">☎</span><div><strong>Legion Health</strong><small>Intake call</small></div></div><div class="message-log">${visible.map(([who,text])=>demoBubble(text,who==='you'?'you':'legion')).join('')}${intake.demoIndex<phoneDemo.length?demoTyping():''}</div></section>`;}
 function draw(){const count=intakeQuestions.filter(q=>intake.answers[q.id]?.trim()).length;const channel=intake.tab==='text'?sms():phone();if(intake.previewOnly&&intake.tab!=='web'){stopDemo();startDemo();root.innerHTML=`<div class="channel-preview"><div class="channel-preview-top"><h1>${intake.tab==='text'?'Text intake':'Phone intake'}</h1></div>${channel}</div>`;const log=root.querySelector('.message-log');if(log)log.scrollTop=log.scrollHeight;return;}stopDemo();root.innerHTML=`<div class="post-intake"><div class="intake-title"><div><div class="eyebrow">Appointment booked</div><h1>Get ready for your visit, ${esc(name)}</h1><p>Prepare at your own pace. The web form is always available; the Text and Phone options are available when Legion reaches out.</p></div></div>${records()}<div class="intake-layout"><div>${intake.error?`<div class="notice" role="alert">${esc(intake.error)}</div>`:''}${intake.reviewed?`<div class="banner" role="status">Your answers are saved for your care team. You can still edit them. Remaining intake sections are listed alongside.</div>`:''}${intake.tab==='web'?web():intake.tab==='text'?sms():phone()}</div><aside class="intake-summary"><section class="intake-card"><h3>Your appointment</h3>${appointment}</section><section class="intake-card"><h3>Before your visit</h3><div class="readiness"><strong>Insurance <span class="status-tag complete">✓ Complete</span></strong><p>${esc(insurance)}</p>${action('insurance','Review insurance')}</div><div class="readiness"><strong>Medical history &amp; check-in <span class="status-tag incomplete">Incomplete</span></strong><p id="intake-count">${count} of ${intakeQuestions.length} preview questions answered</p><progress max="${intakeQuestions.length}" value="${count}"></progress></div><p>Still to complete: remaining medical history, ADHD health history, assessments, emergency contact, ID, recent vital signs, and any required authorizations.</p><p class="fine-print">Your existing forms remain available. Partial answers do not mark a full assessment complete.</p></section></aside></div></div>`;}
 function answer(raw){const q=nextQuestion(intake);if(!q)return;const value=normalizeReply(q,raw);if(!value){intake.error='Please choose one of the listed responses, or use the web form to review your answer.';return;}intake.answers[q.id]=value;intake.reviewed=false;}
 root.onclick=e=>{const button=e.target.closest('[data-intake]');if(!button)return;e.preventDefault();const id=button.dataset.intake;intake.error='';if(['web','text','phone'].includes(id)){intake.tab=id;intake.previewOnly=id!=='web';intake.demoIndex=0;if(id==='text')intake.unread=0;}
 else if(id==='records')intake.records=intake.records==='connected'?'connected':'review';
 else if(id==='connect'){if(!root.querySelector('#record-permission').checked){intake.error='Please confirm permission before connecting your records.';}else{intake.records='connected';intake.imported={pcp:'Dr. Maya Patel · Oakwood Family Care',medications:'Sertraline documented in a prior care summary; dose and current use need confirmation.'};}}
 else if(id==='skip-records'||id==='disconnect'){intake.records='idle';intake.imported={};}
 else if(id==='no-records'){intake.records='empty';intake.imported={};}
 else if(id.startsWith('import-')){const key=id.slice(7);intake.answers[key]=intake.imported[key];delete intake.imported[key];intake.reviewed=false;}
 else if(id==='review')intake.reviewed=true;
 else if(id==='call'){intake.tab='phone';intake.call='active';intake.callConsent=false;}
 else if(id==='text-me'){intake.tab='text';intake.previewOnly=true;intake.demoIndex=0;intake.unread=0;}
 else if(id==='call-me'){intake.tab='phone';intake.previewOnly=true;intake.demoIndex=0;intake.call='active';intake.callConsent=false;}
 else if(id==='call-consent')intake.callConsent=true;
 else if(id==='end-call')intake.call='ended';
 else if(id==='insurance'){reviewInsurance();return;}
 draw();};
 root.oninput=e=>{if(!e.target.dataset.answer)return;intake.answers[e.target.dataset.answer]=e.target.value;intake.reviewed=false;const count=intakeQuestions.filter(q=>intake.answers[q.id]?.trim()).length;root.querySelector('#intake-count').textContent=`${count} of ${intakeQuestions.length} preview questions answered`;root.querySelector('progress').value=count;e.target.nextElementSibling.textContent=e.target.value.trim()?'Saved':'Not answered yet';};
 root.onsubmit=e=>{if(!['sms-reply','phone-reply'].includes(e.target.id))return;e.preventDefault();const raw=new FormData(e.target).get('reply').trim(),cmd=raw.toUpperCase();intake.error='';if(e.target.id==='sms-reply'){
 if(['STOP','UNSUBSCRIBE','CANCEL','END','QUIT'].includes(cmd)){intake.stopped=true;intake.smsConsent=false;}
 else if(cmd==='START'){intake.stopped=false;intake.smsConsent=false;}
 else if(cmd==='HELP'){intake.error='You can switch to the web form at any time. Contact your care team for help. For immediate danger, call 911; for crisis support, call or text 988.';}
 else if(intake.stopped)intake.error='Texts are stopped. Reply START to choose texting again, or use the web form.';
 else if(!intake.smsConsent){intake.smsConsent=true;answer(raw);}
 else if(/suicid|kill myself|hurt myself|harm myself|hurt someone/i.test(raw)){intake.safety=true;intake.error='Please use the crisis guidance below. This inbox is not continuously monitored.';}
 else answer(raw);
 }else answer(raw);draw();};
 draw();
}
